image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: cd modulers && npm install --ignore-scripts && npm run build && npm pack
- init: npm install --ignore-scripts && npm run build
