image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: mysql -D njstest < database/upgrade.sql
- init: cd modulers && npm install --ignore-script ../erable-logger-nodejs-2.0.2.tgz && npm install --ignore-scripts && npm run build && npm pack && cd .. && npm install --ignore-scripts && npm run build
  command: cd modulers && node service.js

