image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- command: cd modulers && npm install --ignore-script ../dist/erable-logger-nodejs-2.0.2.tgz && npm install --ignore-scripts && npm run build && npm pack
- command: npm install --ignore-scripts && npm run build
