image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: sleep 10 && mysql -e "CREATE DATABASE IF NOT EXISTS njstest;" && mysql -e "GRANT ALL PRIVILEGES ON njstest.* TO 'njstest' IDENTIFIED BY 'njstest';"
  command: mysql -D njstest < database/resources/upgrade.sql
- init: cd modulers && npm install --ignore-script ../erable-logger-nodejs-2.0.2.tgz && npm install --ignore-scripts && npm run build && npm pack
  command: node service.js

